USE [PosDocumentation]
GO

/****** Object:  Table [dbo].[tab_APIs]    Script Date: 19.12.2013 17:35:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tab_APIs](
	[fID] [int] NOT NULL IDENTITY(1,1),
	[fApiName] [nvarchar](50) NOT NULL,
	[fDescription] [nvarchar](max) NOT NULL,
	[fDeleted] [bit] NOT NULL,
 CONSTRAINT [PK_tab_APIs] PRIMARY KEY CLUSTERED 
(
	[fID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


