#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiDoc.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PosDocumentation")]
	public partial class PosDocumentationDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PosDocumentationDbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PosDocumentationConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PosDocumentationDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PosDocumentationDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PosDocumentationDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PosDocumentationDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Apis_Delete")]
		public int Apis_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> apiId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apiId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Modules_Update")]
		public int Modules_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> apiId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> moduleId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string moduleName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string author)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apiId, moduleId, moduleName, author);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Apis_GetAll")]
		public ISingleResult<Apis_GetAllResult> Apis_GetAll([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> showDeleted)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), showDeleted);
			return ((ISingleResult<Apis_GetAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Apis_GetById")]
		public ISingleResult<Apis_GetByIdResult> Apis_GetById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> apiId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> revision)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apiId, revision);
			return ((ISingleResult<Apis_GetByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Apis_Insert")]
		public int Apis_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string apiName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string author)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apiName, description, author);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Apis_Update")]
		public int Apis_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> apiId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string apiName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string author)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apiId, apiName, description, author);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetHttpVerbs")]
		public ISingleResult<GetHttpVerbsResult> GetHttpVerbs()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetHttpVerbsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Modules_Delete")]
		public int Modules_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> moduleId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), moduleId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Modules_GetAll")]
		public ISingleResult<Modules_GetAllResult> Modules_GetAll([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> apiId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> showDeleted)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apiId, showDeleted);
			return ((ISingleResult<Modules_GetAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Modules_GetById")]
		public ISingleResult<Modules_GetByIdResult> Modules_GetById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> moduleId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> revision)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), moduleId, revision);
			return ((ISingleResult<Modules_GetByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Modules_Insert")]
		public int Modules_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> apiId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string moduleName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string author)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apiId, moduleName, author);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Modules_GetByName")]
		public ISingleResult<Modules_GetByNameResult> Modules_GetByName([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> apiId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> revision)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apiId, name, revision);
			return ((ISingleResult<Modules_GetByNameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Modules_LookupId")]
		public int Modules_LookupId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> apiId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> result)
		{
			IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apiId, name, result);
			result = ((System.Nullable<int>)(result1.GetParameterValue(2)));
			return ((int)(result1.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Apis_LookupId")]
		public int Apis_LookupId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> result)
		{
			IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, result);
			result = ((System.Nullable<int>)(result1.GetParameterValue(1)));
			return ((int)(result1.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Apis_GetByName")]
		public ISingleResult<Apis_GetByNameResult> Apis_GetByName([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> revision)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, revision);
			return ((ISingleResult<Apis_GetByNameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Modules_GetRevisions")]
		public ISingleResult<Modules_GetRevisionsResult> Modules_GetRevisions([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> apiId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apiId, name);
			return ((ISingleResult<Modules_GetRevisionsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Apis_GetRevisions")]
		public ISingleResult<Apis_GetRevisionsResult> Apis_GetRevisions([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> apiId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apiId);
			return ((ISingleResult<Apis_GetRevisionsResult>)(result.ReturnValue));
		}
	}
	
	public partial class Apis_GetAllResult
	{
		
		private int _fID;
		
		private string _fApiName;
		
		private string _fDescription;
		
		private bool _fDeleted;
		
		public Apis_GetAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fID", DbType="Int NOT NULL")]
		public int fID
		{
			get
			{
				return this._fID;
			}
			set
			{
				if ((this._fID != value))
				{
					this._fID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fApiName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fApiName
		{
			get
			{
				return this._fApiName;
			}
			set
			{
				if ((this._fApiName != value))
				{
					this._fApiName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDescription", DbType="NVarChar(MAX)")]
		public string fDescription
		{
			get
			{
				return this._fDescription;
			}
			set
			{
				if ((this._fDescription != value))
				{
					this._fDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDeleted", DbType="Bit NOT NULL")]
		public bool fDeleted
		{
			get
			{
				return this._fDeleted;
			}
			set
			{
				if ((this._fDeleted != value))
				{
					this._fDeleted = value;
				}
			}
		}
	}
	
	public partial class Apis_GetByIdResult
	{
		
		private int _fID;
		
		private string _fApiName;
		
		private string _fDescription;
		
		private System.DateTime _fChangeDate;
		
		private string _fAuthor;
		
		private bool _fDeleted;
		
		private System.Nullable<long> _fRevisionNumber;
		
		public Apis_GetByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fID", DbType="Int NOT NULL")]
		public int fID
		{
			get
			{
				return this._fID;
			}
			set
			{
				if ((this._fID != value))
				{
					this._fID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fApiName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fApiName
		{
			get
			{
				return this._fApiName;
			}
			set
			{
				if ((this._fApiName != value))
				{
					this._fApiName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDescription", DbType="NVarChar(MAX)")]
		public string fDescription
		{
			get
			{
				return this._fDescription;
			}
			set
			{
				if ((this._fDescription != value))
				{
					this._fDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fChangeDate", DbType="DateTime NOT NULL")]
		public System.DateTime fChangeDate
		{
			get
			{
				return this._fChangeDate;
			}
			set
			{
				if ((this._fChangeDate != value))
				{
					this._fChangeDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAuthor", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fAuthor
		{
			get
			{
				return this._fAuthor;
			}
			set
			{
				if ((this._fAuthor != value))
				{
					this._fAuthor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDeleted", DbType="Bit NOT NULL")]
		public bool fDeleted
		{
			get
			{
				return this._fDeleted;
			}
			set
			{
				if ((this._fDeleted != value))
				{
					this._fDeleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fRevisionNumber", DbType="BigInt")]
		public System.Nullable<long> fRevisionNumber
		{
			get
			{
				return this._fRevisionNumber;
			}
			set
			{
				if ((this._fRevisionNumber != value))
				{
					this._fRevisionNumber = value;
				}
			}
		}
	}
	
	public partial class GetHttpVerbsResult
	{
		
		private int _fID;
		
		private string _fHttpVerb;
		
		public GetHttpVerbsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fID", DbType="Int NOT NULL")]
		public int fID
		{
			get
			{
				return this._fID;
			}
			set
			{
				if ((this._fID != value))
				{
					this._fID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fHttpVerb", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fHttpVerb
		{
			get
			{
				return this._fHttpVerb;
			}
			set
			{
				if ((this._fHttpVerb != value))
				{
					this._fHttpVerb = value;
				}
			}
		}
	}
	
	public partial class Modules_GetAllResult
	{
		
		private int _fID;
		
		private string _fModuleName;
		
		private bool _fDeleted;
		
		public Modules_GetAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fID", DbType="Int NOT NULL")]
		public int fID
		{
			get
			{
				return this._fID;
			}
			set
			{
				if ((this._fID != value))
				{
					this._fID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fModuleName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fModuleName
		{
			get
			{
				return this._fModuleName;
			}
			set
			{
				if ((this._fModuleName != value))
				{
					this._fModuleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDeleted", DbType="Bit NOT NULL")]
		public bool fDeleted
		{
			get
			{
				return this._fDeleted;
			}
			set
			{
				if ((this._fDeleted != value))
				{
					this._fDeleted = value;
				}
			}
		}
	}
	
	public partial class Modules_GetByIdResult
	{
		
		private int _fID;
		
		private string _fModuleName;
		
		private System.DateTime _fChangeDate;
		
		private string _fAuthor;
		
		private bool _fDeleted;
		
		private System.Nullable<long> _fRevisionNumber;
		
		public Modules_GetByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fID", DbType="Int NOT NULL")]
		public int fID
		{
			get
			{
				return this._fID;
			}
			set
			{
				if ((this._fID != value))
				{
					this._fID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fModuleName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fModuleName
		{
			get
			{
				return this._fModuleName;
			}
			set
			{
				if ((this._fModuleName != value))
				{
					this._fModuleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fChangeDate", DbType="DateTime NOT NULL")]
		public System.DateTime fChangeDate
		{
			get
			{
				return this._fChangeDate;
			}
			set
			{
				if ((this._fChangeDate != value))
				{
					this._fChangeDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAuthor", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fAuthor
		{
			get
			{
				return this._fAuthor;
			}
			set
			{
				if ((this._fAuthor != value))
				{
					this._fAuthor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDeleted", DbType="Bit NOT NULL")]
		public bool fDeleted
		{
			get
			{
				return this._fDeleted;
			}
			set
			{
				if ((this._fDeleted != value))
				{
					this._fDeleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fRevisionNumber", DbType="BigInt")]
		public System.Nullable<long> fRevisionNumber
		{
			get
			{
				return this._fRevisionNumber;
			}
			set
			{
				if ((this._fRevisionNumber != value))
				{
					this._fRevisionNumber = value;
				}
			}
		}
	}
	
	public partial class Modules_GetByNameResult
	{
		
		private int _fID;
		
		private string _fModuleName;
		
		private System.DateTime _fChangeDate;
		
		private string _fAuthor;
		
		private bool _fDeleted;
		
		private System.Nullable<long> _fRevisionNumber;
		
		public Modules_GetByNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fID", DbType="Int NOT NULL")]
		public int fID
		{
			get
			{
				return this._fID;
			}
			set
			{
				if ((this._fID != value))
				{
					this._fID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fModuleName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fModuleName
		{
			get
			{
				return this._fModuleName;
			}
			set
			{
				if ((this._fModuleName != value))
				{
					this._fModuleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fChangeDate", DbType="DateTime NOT NULL")]
		public System.DateTime fChangeDate
		{
			get
			{
				return this._fChangeDate;
			}
			set
			{
				if ((this._fChangeDate != value))
				{
					this._fChangeDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAuthor", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fAuthor
		{
			get
			{
				return this._fAuthor;
			}
			set
			{
				if ((this._fAuthor != value))
				{
					this._fAuthor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDeleted", DbType="Bit NOT NULL")]
		public bool fDeleted
		{
			get
			{
				return this._fDeleted;
			}
			set
			{
				if ((this._fDeleted != value))
				{
					this._fDeleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fRevisionNumber", DbType="BigInt")]
		public System.Nullable<long> fRevisionNumber
		{
			get
			{
				return this._fRevisionNumber;
			}
			set
			{
				if ((this._fRevisionNumber != value))
				{
					this._fRevisionNumber = value;
				}
			}
		}
	}
	
	public partial class Apis_GetByNameResult
	{
		
		private int _fID;
		
		private string _fApiName;
		
		private string _fDescription;
		
		private System.DateTime _fChangeDate;
		
		private string _fAuthor;
		
		private bool _fDeleted;
		
		private System.Nullable<long> _fRevisionNumber;
		
		public Apis_GetByNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fID", DbType="Int NOT NULL")]
		public int fID
		{
			get
			{
				return this._fID;
			}
			set
			{
				if ((this._fID != value))
				{
					this._fID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fApiName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fApiName
		{
			get
			{
				return this._fApiName;
			}
			set
			{
				if ((this._fApiName != value))
				{
					this._fApiName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDescription", DbType="NVarChar(MAX)")]
		public string fDescription
		{
			get
			{
				return this._fDescription;
			}
			set
			{
				if ((this._fDescription != value))
				{
					this._fDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fChangeDate", DbType="DateTime NOT NULL")]
		public System.DateTime fChangeDate
		{
			get
			{
				return this._fChangeDate;
			}
			set
			{
				if ((this._fChangeDate != value))
				{
					this._fChangeDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAuthor", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fAuthor
		{
			get
			{
				return this._fAuthor;
			}
			set
			{
				if ((this._fAuthor != value))
				{
					this._fAuthor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDeleted", DbType="Bit NOT NULL")]
		public bool fDeleted
		{
			get
			{
				return this._fDeleted;
			}
			set
			{
				if ((this._fDeleted != value))
				{
					this._fDeleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fRevisionNumber", DbType="BigInt")]
		public System.Nullable<long> fRevisionNumber
		{
			get
			{
				return this._fRevisionNumber;
			}
			set
			{
				if ((this._fRevisionNumber != value))
				{
					this._fRevisionNumber = value;
				}
			}
		}
	}
	
	public partial class Modules_GetRevisionsResult
	{
		
		private int _fID;
		
		private string _fModuleName;
		
		private System.DateTime _fChangeDate;
		
		private string _fAuthor;
		
		private bool _fDeleted;
		
		private System.Nullable<long> _fRevisionNumber;
		
		public Modules_GetRevisionsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fID", DbType="Int NOT NULL")]
		public int fID
		{
			get
			{
				return this._fID;
			}
			set
			{
				if ((this._fID != value))
				{
					this._fID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fModuleName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fModuleName
		{
			get
			{
				return this._fModuleName;
			}
			set
			{
				if ((this._fModuleName != value))
				{
					this._fModuleName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fChangeDate", DbType="DateTime NOT NULL")]
		public System.DateTime fChangeDate
		{
			get
			{
				return this._fChangeDate;
			}
			set
			{
				if ((this._fChangeDate != value))
				{
					this._fChangeDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAuthor", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fAuthor
		{
			get
			{
				return this._fAuthor;
			}
			set
			{
				if ((this._fAuthor != value))
				{
					this._fAuthor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDeleted", DbType="Bit NOT NULL")]
		public bool fDeleted
		{
			get
			{
				return this._fDeleted;
			}
			set
			{
				if ((this._fDeleted != value))
				{
					this._fDeleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fRevisionNumber", DbType="BigInt")]
		public System.Nullable<long> fRevisionNumber
		{
			get
			{
				return this._fRevisionNumber;
			}
			set
			{
				if ((this._fRevisionNumber != value))
				{
					this._fRevisionNumber = value;
				}
			}
		}
	}
	
	public partial class Apis_GetRevisionsResult
	{
		
		private int _fID;
		
		private string _fApiName;
		
		private string _fDescription;
		
		private System.DateTime _fChangeDate;
		
		private string _fAuthor;
		
		private bool _fDeleted;
		
		private System.Nullable<long> _fRevisionNumber;
		
		public Apis_GetRevisionsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fID", DbType="Int NOT NULL")]
		public int fID
		{
			get
			{
				return this._fID;
			}
			set
			{
				if ((this._fID != value))
				{
					this._fID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fApiName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fApiName
		{
			get
			{
				return this._fApiName;
			}
			set
			{
				if ((this._fApiName != value))
				{
					this._fApiName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDescription", DbType="NVarChar(MAX)")]
		public string fDescription
		{
			get
			{
				return this._fDescription;
			}
			set
			{
				if ((this._fDescription != value))
				{
					this._fDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fChangeDate", DbType="DateTime NOT NULL")]
		public System.DateTime fChangeDate
		{
			get
			{
				return this._fChangeDate;
			}
			set
			{
				if ((this._fChangeDate != value))
				{
					this._fChangeDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fAuthor", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fAuthor
		{
			get
			{
				return this._fAuthor;
			}
			set
			{
				if ((this._fAuthor != value))
				{
					this._fAuthor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDeleted", DbType="Bit NOT NULL")]
		public bool fDeleted
		{
			get
			{
				return this._fDeleted;
			}
			set
			{
				if ((this._fDeleted != value))
				{
					this._fDeleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fRevisionNumber", DbType="BigInt")]
		public System.Nullable<long> fRevisionNumber
		{
			get
			{
				return this._fRevisionNumber;
			}
			set
			{
				if ((this._fRevisionNumber != value))
				{
					this._fRevisionNumber = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
