#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiDoc.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PosDocumentation")]
	public partial class PosDocumentationDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PosDocumentationDbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PosDocumentationConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PosDocumentationDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PosDocumentationDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PosDocumentationDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PosDocumentationDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAPIs")]
		public ISingleResult<GetAPIsResult> GetAPIs()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAPIsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetMethodDetails")]
		public ISingleResult<GetMethodDetailsResult> GetMethodDetails([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> methodId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), methodId);
			return ((ISingleResult<GetMethodDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetMethodsForService")]
		public ISingleResult<GetMethodsForServiceResult> GetMethodsForService([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> serviceId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), serviceId);
			return ((ISingleResult<GetMethodsForServiceResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetModulesForApi")]
		public ISingleResult<GetModulesForApiResult> GetModulesForApi([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApiId", DbType="Int")] System.Nullable<int> apiId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apiId);
			return ((ISingleResult<GetModulesForApiResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetAPIsResult
	{
		
		private int _fID;
		
		private string _fApiName;
		
		private string _fDescription;
		
		public GetAPIsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fID", DbType="Int NOT NULL")]
		public int fID
		{
			get
			{
				return this._fID;
			}
			set
			{
				if ((this._fID != value))
				{
					this._fID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fApiName", DbType="NVarChar(50)")]
		public string fApiName
		{
			get
			{
				return this._fApiName;
			}
			set
			{
				if ((this._fApiName != value))
				{
					this._fApiName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDescription", DbType="VarChar(MAX)")]
		public string fDescription
		{
			get
			{
				return this._fDescription;
			}
			set
			{
				if ((this._fDescription != value))
				{
					this._fDescription = value;
				}
			}
		}
	}
	
	public partial class GetMethodDetailsResult
	{
		
		private int _fID;
		
		private int _frServiceId;
		
		private string _fMethodName;
		
		private int _frHttpVerb;
		
		private bool _fRequiresAuthentication;
		
		private bool _fRequiresAuthorization;
		
		private string _fRequestSample;
		
		private string _fResponseSampe;
		
		private string _fDescription;
		
		public GetMethodDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fID", DbType="Int NOT NULL")]
		public int fID
		{
			get
			{
				return this._fID;
			}
			set
			{
				if ((this._fID != value))
				{
					this._fID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_frServiceId", DbType="Int NOT NULL")]
		public int frServiceId
		{
			get
			{
				return this._frServiceId;
			}
			set
			{
				if ((this._frServiceId != value))
				{
					this._frServiceId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fMethodName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string fMethodName
		{
			get
			{
				return this._fMethodName;
			}
			set
			{
				if ((this._fMethodName != value))
				{
					this._fMethodName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_frHttpVerb", DbType="Int NOT NULL")]
		public int frHttpVerb
		{
			get
			{
				return this._frHttpVerb;
			}
			set
			{
				if ((this._frHttpVerb != value))
				{
					this._frHttpVerb = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fRequiresAuthentication", DbType="Bit NOT NULL")]
		public bool fRequiresAuthentication
		{
			get
			{
				return this._fRequiresAuthentication;
			}
			set
			{
				if ((this._fRequiresAuthentication != value))
				{
					this._fRequiresAuthentication = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fRequiresAuthorization", DbType="Bit NOT NULL")]
		public bool fRequiresAuthorization
		{
			get
			{
				return this._fRequiresAuthorization;
			}
			set
			{
				if ((this._fRequiresAuthorization != value))
				{
					this._fRequiresAuthorization = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fRequestSample", DbType="VarChar(MAX)")]
		public string fRequestSample
		{
			get
			{
				return this._fRequestSample;
			}
			set
			{
				if ((this._fRequestSample != value))
				{
					this._fRequestSample = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fResponseSampe", DbType="VarChar(MAX)")]
		public string fResponseSampe
		{
			get
			{
				return this._fResponseSampe;
			}
			set
			{
				if ((this._fResponseSampe != value))
				{
					this._fResponseSampe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fDescription", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string fDescription
		{
			get
			{
				return this._fDescription;
			}
			set
			{
				if ((this._fDescription != value))
				{
					this._fDescription = value;
				}
			}
		}
	}
	
	public partial class GetMethodsForServiceResult
	{
		
		private int _fID;
		
		private string _fMethodName;
		
		private int _frHttpVerb;
		
		public GetMethodsForServiceResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fID", DbType="Int NOT NULL")]
		public int fID
		{
			get
			{
				return this._fID;
			}
			set
			{
				if ((this._fID != value))
				{
					this._fID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fMethodName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string fMethodName
		{
			get
			{
				return this._fMethodName;
			}
			set
			{
				if ((this._fMethodName != value))
				{
					this._fMethodName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_frHttpVerb", DbType="Int NOT NULL")]
		public int frHttpVerb
		{
			get
			{
				return this._frHttpVerb;
			}
			set
			{
				if ((this._frHttpVerb != value))
				{
					this._frHttpVerb = value;
				}
			}
		}
	}
	
	public partial class GetModulesForApiResult
	{
		
		private int _fID;
		
		private string _fServiceName;
		
		public GetModulesForApiResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fID", DbType="Int NOT NULL")]
		public int fID
		{
			get
			{
				return this._fID;
			}
			set
			{
				if ((this._fID != value))
				{
					this._fID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fServiceName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fServiceName
		{
			get
			{
				return this._fServiceName;
			}
			set
			{
				if ((this._fServiceName != value))
				{
					this._fServiceName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
