<?xml version="1.0" encoding="utf-8"?><Database Name="PosDocumentation" Class="PosDocumentationDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ihayden-PC;Initial Catalog=PosDocumentation;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PosDocumentationConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.Apis_Delete" Method="Apis_Delete">
    <Parameter Name="apiId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Modules_Update" Method="Modules_Update">
    <Parameter Name="apiId" Type="System.Int32" DbType="Int" />
    <Parameter Name="moduleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="moduleName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="author" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Apis_GetAll" Method="Apis_GetAll">
    <Parameter Name="showDeleted" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="Apis_GetAllResult">
      <Column Name="fID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fApiName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Apis_GetById" Method="Apis_GetById">
    <Parameter Name="apiId" Type="System.Int32" DbType="Int" />
    <Parameter Name="revision" Type="System.Int32" DbType="Int" />
    <ElementType Name="Apis_GetByIdResult">
      <Column Name="fID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fApiName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fChangeDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fAuthor" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fRevisionNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Apis_Insert" Method="Apis_Insert">
    <Parameter Name="apiName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="description" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="author" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Apis_Update" Method="Apis_Update">
    <Parameter Name="apiId" Type="System.Int32" DbType="Int" />
    <Parameter Name="apiName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="description" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="author" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetHttpVerbs" Method="GetHttpVerbs">
    <ElementType Name="GetHttpVerbsResult">
      <Column Name="fID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fHttpVerb" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Modules_Delete" Method="Modules_Delete">
    <Parameter Name="moduleId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Modules_GetAll" Method="Modules_GetAll">
    <Parameter Name="apiId" Type="System.Int32" DbType="Int" />
    <Parameter Name="showDeleted" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="Modules_GetAllResult">
      <Column Name="fID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fModuleName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Modules_GetById" Method="Modules_GetById">
    <Parameter Name="moduleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="revision" Type="System.Int32" DbType="Int" />
    <ElementType Name="Modules_GetByIdResult">
      <Column Name="fID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fModuleName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fChangeDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fAuthor" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fRevisionNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Modules_Insert" Method="Modules_Insert">
    <Parameter Name="apiId" Type="System.Int32" DbType="Int" />
    <Parameter Name="moduleName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="author" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Modules_GetByName" Method="Modules_GetByName">
    <Parameter Name="apiId" Type="System.Int32" DbType="Int" />
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="revision" Type="System.Int32" DbType="Int" />
    <ElementType Name="Modules_GetByNameResult">
      <Column Name="fID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fModuleName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fChangeDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fAuthor" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fRevisionNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Modules_LookupId" Method="Modules_LookupId">
    <Parameter Name="apiId" Type="System.Int32" DbType="Int" />
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="result" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Apis_LookupId" Method="Apis_LookupId">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="result" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Apis_GetByName" Method="Apis_GetByName">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="revision" Type="System.Int32" DbType="Int" />
    <ElementType Name="Apis_GetByNameResult">
      <Column Name="fID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fApiName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fChangeDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fAuthor" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fRevisionNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Modules_GetRevisions" Method="Modules_GetRevisions">
    <Parameter Name="apiId" Type="System.Int32" DbType="Int" />
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="Modules_GetRevisionsResult">
      <Column Name="fID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fModuleName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fChangeDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fAuthor" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fRevisionNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Apis_GetRevisions" Method="Apis_GetRevisions">
    <Parameter Name="apiId" Type="System.Int32" DbType="Int" />
    <ElementType Name="Apis_GetRevisionsResult">
      <Column Name="fID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fApiName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fChangeDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fAuthor" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fRevisionNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>